apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-service
  labels:
    app: code-execution-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-execution-service
  template:
    metadata:
      labels:
        app: code-execution-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: code-execution-service
          image: 239861161036.dkr.ecr.eu-central-1.amazonaws.com/codesnap/code-execution-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: LOGFIRE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logfire-secrets
                  key: write-token
            - name: LOGFIRE_SERVICE_NAME
              value: "code-execution-service"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"

        # Docker-in-Docker Sidecar
        - name: dind
          image: docker:24-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker

      volumes:
        - name: docker-graph-storage
          emptyDir: {}
