apiVersion: v1
kind: Service
metadata:
  name: code-execution-service
  labels:
    app: code-execution-service
spec:
  selector:
    app: code-execution-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
